/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.mycompany.task4;

/**
 *
 * @author mabdu
 */
public class Task4 {

    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
/*
 * @author nawab
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class DatabaseConnection.java{

    private static final String URL = "jdbc:mysql://localhost:3306/Sanju";
    private static final String USER = "root";
    private static final String PASSWORD = "Sanju@12345";

    public static Connection getConnection() {
        Connection connection = null;
        try {
            // Load the MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Establish the connection
            connection = DriverManager.getConnection(URL, USER, PASSWORD);
            System.out.println("Connected to MySQL database!");
        } catch (ClassNotFoundException | SQLException e) {
            System.err.println("Connection error: " + e.getMessage());
        }
        return connection;
    }

    public static void main(String[] args) {
        getConnection();
    }
}
public Homepage() {
    initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    viewProfileButton = new javax.swing.JButton();
    settingsButton = new javax.swing.JButton();
    logoutButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Welcome to the Homepage");
    jLabel1.setToolTipText("");

    jLabel2.setText("Hello, User!");
    jLabel2.setToolTipText("");

    viewProfileButton.setText("View Profile");
    viewProfileButton.setToolTipText("");

    settingsButton.setText("Settings");

    logoutButton.setText("Logout");

    // (Layout code would follow this, possibly auto-generated)
}
// </editor-fold>

